### ISSUE TITLE
Sweden - tv-tabla.se

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#110] opened 2021-10-14 08:30 UTC
@Robinmcgvr Missing 11th October 2021

**Comment by Robinmcgvr** [comment] 2021-10-14 09:09
Thanks as I check the data mondays and fridays this hadn't been logged yet - have added it to Matteo's chart

**Comment by Robinmcgvr** [comment] 2021-10-14 09:27
To give further background - the robots pull data in at different times of day so although data was checked on monday morning because data for sweden comes through in the afternoon, it wouldn't be visible as being missing in the morning.

**Comment by Robinmcgvr** [comment] 2021-10-18 10:21
@Lynne12 
Still no progress on this one, not heard anything back from Matteo, if I don't hear anything today I will chase him up again

**Comment by Lynne12** [comment] 2021-10-20 11:22
Further data missing 12-18 October 2021

**Comment by Robinmcgvr** [comment] 2021-10-20 11:25
Thanks I have reported this and emailed to Matteo earlier in week, still not getting anything back from him on that one though - don't know what the problem is

**Comment by Robinmcgvr** [comment] 2021-10-21 11:42
@Lynne12 
Good and bad news on this one.
Robot is now fixed - data has not been recovered and won't be.
BUT - V Film Premiere is available for the dates 11-19/10 from viasat.se

**Comment by Lynne12** [comment] 2021-10-27 07:59
V Film Premiere loaded, 11-19 October.

**Closed as completed** 2021-10-27 08:02 UTC
